/**
 * Seed the catalog from a self-contained JSON snapshot (`seed-data.json`),
 * generated by `npm run gen:seed` from the storefront's mock catalog. Reading
 * JSON (rather than importing ../../src/app TS) keeps the seed portable — it
 * runs anywhere with no cross-folder import and no ts-node path juggling.
 *
 * Byte-identical to the mock, including the SVG data-URI galleries.
 */
import { readFileSync } from 'fs';
import { join } from 'path';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface SeedProduct {
  id: string;
  slug: string;
  name: string;
  brand: string;
  categoryId: string;
  description: string;
  price: number;
  mrp: number;
  rating: number;
  ratingCount: number;
  inStock: boolean;
  stockCount: number;
  colors?: string[];
  sizes?: string[];
  badges?: string[];
  ageGroup?: string;
  gender?: string;
  soldCount: number;
  createdAt: string;
  images: unknown;
  specs?: unknown;
  variantOptions?: unknown;
  reviews?: unknown;
}

interface SeedCategory {
  id: string;
  slug: string;
  name: string;
  image: string;
  parentId?: string;
}

async function main() {
  // Skip if already seeded — makes it safe to run on every boot (the deploy
  // start command calls this). Pass --force to reseed anyway.
  const force = process.argv.includes('--force');
  const existing = await prisma.product.count();
  if (existing > 0 && !force) {
    console.log(`Catalog already seeded (${existing} products) — skipping.`);
    return;
  }

  console.log('Seeding Jiaranest catalog…');

  const data = JSON.parse(readFileSync(join(__dirname, 'seed-data.json'), 'utf8')) as {
    categories: SeedCategory[];
    products: SeedProduct[];
  };

  // Clear then reload (reached only when empty, or with --force).
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();

  // Parents before children (self-relation FK).
  const parents = data.categories.filter((c) => !c.parentId);
  const children = data.categories.filter((c) => c.parentId);
  for (const c of [...parents, ...children]) {
    await prisma.category.create({
      data: {
        id: c.id,
        slug: c.slug,
        name: c.name,
        image: c.image,
        parentId: c.parentId ?? null,
      },
    });
  }
  console.log(`  ${data.categories.length} categories`);

  for (const p of data.products) {
    await prisma.product.create({
      data: {
        id: p.id,
        slug: p.slug,
        name: p.name,
        brand: p.brand,
        categoryId: p.categoryId,
        description: p.description,
        price: p.price,
        mrp: p.mrp,
        rating: p.rating,
        ratingCount: p.ratingCount,
        inStock: p.inStock,
        stockCount: p.stockCount,
        colors: p.colors ?? [],
        sizes: p.sizes ?? [],
        badges: p.badges ?? [],
        ageGroup: p.ageGroup ?? null,
        gender: p.gender ?? null,
        soldCount: p.soldCount,
        createdAt: new Date(p.createdAt),
        images: p.images as object,
        specs: (p.specs ?? undefined) as object,
        variantOptions: (p.variantOptions ?? undefined) as object,
        reviews: (p.reviews ?? undefined) as object,
      },
    });
  }
  console.log(`  ${data.products.length} products`);
  console.log('Done.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
