// Generates src/app/core/version.ts from package.json's "version" so the app
// always displays the current version without bundling package.json.
// Runs automatically before `build` / `start` via the npm "pre" hooks.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
const out = resolve(root, 'src/app/core/version.ts');

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.\n` +
    `// Sourced from package.json "version" on each build.\n` +
    `export const APP_VERSION = '${pkg.version}';\n`,
);
console.log(`version.ts → ${pkg.version}`);
